### ISSUE TITLE
An unexpected error occured: Calculated digest at EOF 

### ISSUE THREAD

**Issue by SmirnovDevOps** [w2c/letsencrypt-esxi#10]
Hi
It's during install

**Comment by SmirnovDevOps** [comment]
esxi 6.5

**Comment by Churro** [comment]
Which release are you using? Does it happen with 1.0 and 1.1.0?

**Comment by SmirnovDevOps** [comment]
Calculated digest at EOF does not match expected result: 008a9b8e291e7f38ba10f33dee05632e7119c41c7c6b62e86e7a38711ac25222 calculated, 8b3901e1c59fe4afd97d6f04d731deb76e50199f803ba8262863e8f6ac8ea7d2 expected.
       vibs = web-wack-creations_bootbank_w2c-letsencrypt-esxi_1.1.0-0.0.0
 Please refer to the log file for more details.

**Comment by SmirnovDevOps** [comment]
1.0 OK

Installation Result
   Message: Operation finished successfully.
   Reboot Required: false
   VIBs Installed: web-wack-creations_bootbank_w2c-letsencrypt-esxi_1.0.0-0.0.0
   VIBs Removed:
   VIBs Skipped:
[root@localhost:/tmp]

**Comment by SmirnovDevOps** [comment]
1.0 installed and configured, working well
Thank you for your work!

can you write and vib?
that starts each 5 min, checks an list of  fqdn, convert it in ip addresses list and add that list in firewall rule vspher client connections?

**Comment by SmirnovDevOps** [comment]
would be very handy, to restrict connections only from dynamic dns names

**Comment by Churro** [comment]
> Calculated digest at EOF does not match expected result: 008a9b8e291e7f38ba10f33dee05632e7119c41c7c6b62e86e7a38711ac25222 calculated, 8b3901e1c59fe4afd97d6f04d731deb76e50199f803ba8262863e8f6ac8ea7d2 expected. vibs = web-wack-creations_bootbank_w2c-letsencrypt-esxi_1.1.0-0.0.0 Please refer to the log file for more details.

Hmm, then it seems that 6.5 doesn't support gzipped SHA-256 digests. If you want to give version 1.1.0 another try, you could test with: `esxcli software vib install -v /tmp/w2c-letsencrypt-esxi.vib -f --no-sig-check`

**Comment by SmirnovDevOps** [comment]
--no-sig-check
already tried

**Comment by SmirnovDevOps** [comment]
nope

**Comment by SmirnovDevOps** [comment]
--no-sig-check
Does not help
