### ISSUE TITLE
tried to install on esxi 5.5 - and now can't uninstall it

### ISSUE THREAD

**Issue by SmirnovDevOps** [w2c/letsencrypt-esxi#12]
Hi
tried to install on esxi 5.5 - and now can't uninstall it

getting this error

~ # esxcli software vib remove -n w2c-letsencrypt-esxi
 [InstallationError]
 Error in running rm /tardisks/payload1.v00:
 Return code: 1
 Output: rm: can't remove '/tardisks/payload1.v00': Device or resource busy

 It is not safe to continue. Please reboot the host immediately to discard the unfinished update.
 Please refer to the log file for more details.
~ #

**Comment by horfic** [comment]
Hi,
unfortunately esxi 5.5 was not tested and we are not planning on supporting this esxi version.

However, did you try to reboot the esxi server as mentioned in your output?
What information is written in the mentioned log file for more details?

PS: You can check what process is currently using this file by using the "lsof" command to get the process id

kind regards

**Comment by SmirnovDevOps** [comment]
already reboot the host
after reboot the same error

/tardisks/payload1.v00': Device or resource busy

log file content
/var/log/esxcli.log

[2023-02-08 07:47:40,214 root ERROR] remove failed:  [InstallationError]
 Error in running rm /tardisks/payload1.v00:
 Return code: 1
 Output: rm: can't remove '/tardisks/payload1.v00': Device or resource busy
 
 It is not safe to continue. Please reboot the host immediately to discard the unfinished update.
 Please refer to the log file for more details.
[2023-02-08 08:27:12,566 root ERROR] remove failed:  [InstallationError]
 Error in running rm /tardisks/payload1.v00:
 Return code: 1
 Output: rm: can't remove '/tardisks/payload1.v00': Device or resource busy
 
 It is not safe to continue. Please reboot the host immediately to discard the unfinished update.
 Please refer to the log file for more details.

**Comment by SmirnovDevOps** [comment]
how to stop the process? that use /tardisks/payload1.v00

**Comment by horfic** [comment]
first you need to find out with lsof command which process (process id) is currently accessing this file.
afterwards you can kill the process kill -9 {process id}

be careful that the process you are killing is not something important

**Comment by SmirnovDevOps** [comment]
i run
lsof -d txt > lsof.txt
[lsof.txt](https://github.com/w2c/letsencrypt-esxi/files/10684184/lsof.txt)

can't find any process  /tardisks/payload1.v00

**Comment by horfic** [comment]
why don't you run
`lsof /tardisks/payload1.v00`

that should provide you directly the info what process is accessing it

**Comment by SmirnovDevOps** [comment]
Maybe something is wrong, but then it gives me a list of all processes

lsof /tardisks/payload1.v00 -d txt > lsof2.txt
[lsof2.txt](https://github.com/w2c/letsencrypt-esxi/files/10684386/lsof2.txt)

**Comment by horfic** [comment]
is your server in maintenance mode?

can you try `esxcli software vib remove --maintenance-mode -n w2c-letsencrypt-esxi`

**Comment by SmirnovDevOps** [comment]
if i start the script
/etc/init.d/w2c-letsencrypt start


it gives error
sh: can't kill pid 64926: No such process

something wrong with process name/ID

**Comment by SmirnovDevOps** [comment]
> is your server in maintenance mode?
> 
> can you try `esxcli software vib remove --maintenance-mode -n w2c-letsencrypt-esxi`

i heve to put my server in maintenance before?

**Comment by Churro** [comment]
Hi, I have no idea what causes your problems but I can tell you for sure that 5.5 is not supported. It doesn't run the `acme_tiny.py` script.

**Comment by SmirnovDevOps** [comment]
solved, thanks
