### ISSUE TITLE
DNS challenge?

### ISSUE THREAD

**Issue by NoLooseEnds** [w2c/letsencrypt-esxi#2]
Do you think it would be possible to use the DNS challenge instead of HTTP? Then not public facing servers would also work.

I found this project that could be of help: https://github.com/Trim/acme-dns-tiny/

**Comment by Churro** [comment]
I don't think, unfortunately. The project you linked relies on the [dnspython](https://www.dnspython.org ) toolkit (see [here](https://github.com/Trim/acme-dns-tiny/blob/9aebb03c8b0e58eee281acfdf9c132b87f81ecb0/acme_dns_tiny.py#L7)), which is not available on any python interpreter shipped with ESXi.

The only way I can imagine to get such a lib working on ESXi would be to manually transfer it via `scp` from another host after running the install script. In any case, nothing that could integrated into this script.

**Comment by nkelemen18** [comment]
What do you think about acme.sh? https://github.com/acmesh-official/acme.sh

**Comment by Churro** [comment]
Doesn't work currently, as it depends on Unix tools like [tr](https://linux.die.net/man/1/tr), which isn't shipped with ESXi.

**Comment by jacobswin** [comment]
Could I use other port instead of default 443 as my ISP blocked it, like "abc.esxi.com:4443" ?

**Comment by Churro** [comment]
> Could I use other port instead of default 443 as my ISP blocked it, like "abc.esxi.com:4443" ?

Yes, I think so. Just give it a try.

**Comment by jacobswin** [comment]
I tried to use port 2222 and use the syntax like, 
esxcfg-advcfg -s aaa.bbb.com:2222 /Misc/hostname
to change the new hostname. But the result seems not working. It shows the port 80 that be still requesting.
