### ISSUE TITLE
Cannot uninstall on ESXi 8u1

### ISSUE THREAD

**Issue by phocean** [w2c/letsencrypt-esxi#23]
Hi,

I had it installed on ESXi 8u1 and not only did it not work with the challenge, but now I cannot uninstall it.

Basically I am stuck with it permanently failing, restoring self-signed certificates instead of my custom valid ones...

Any idea please ?

```
esxcli software vib remove --maintenance-mode -n w2c-l
etsencrypt-esxi
 [Exception]
 Busy
 Please refer to the log file for more details.
```

**Comment by Churro** [comment]
Could you please take a look at `/var/log/syslog.log`? The output you posted reveals no clues about the issue you're facing.

**Comment by horfic** [comment]
close due to inactivity by creator
