### ISSUE TITLE
Update to use DNS Challenge

### ISSUE THREAD

**Issue by derekoharrow** [w2c/letsencrypt-esxi#24]
Exposing an ESXi server to the public internet really isn't a good idea.

LetsEncrypt permits the use of a DNS Challenge.

Could you update this to enable the use of that instead?

thanks!

**Comment by Churro** [comment]
It would be great to have this functionality but unfortunately there are some hard blockers, see https://github.com/w2c/letsencrypt-esxi/issues/2.
