### ISSUE TITLE
Issues with Firewall

### ISSUE THREAD

**Issue by nvram93** [w2c/letsencrypt-esxi#29]
Hey there, 

I've got both "vSphere Web Access" and "vSphere Web Client" limited to my own IPs, which makes it impossible to pass the challenge automatically, so i've got to disable the firewall in esxi first and then need to execute the script manually and then need to enable the firewall again.

is there some way you can automate this, so your script checks if the firewall for both services is active and disables it before it proceeds to order the certificate? Also it should activate the firewall again when the certificate is installed successfully.

best regards

**Comment by Churro** [comment]
Should be possible, yes. If I'm not mistaken your request is a duplicate of https://github.com/w2c/letsencrypt-esxi/discussions/25.

**Comment by nvram93** [comment]
yes, you're right. going to close this
