### ISSUE TITLE
DNS-01 challenge

### ISSUE THREAD

**Issue by MrakCZ** [w2c/letsencrypt-esxi#30]
Hello, what about DNS challenge for cloudflare for example? It will be much easier and safer than open 80 and 443 port in my firewall and redirecting it to esxi for issuing certificate. I found few solutions, but it's too complicated for every three months renewal. Your vib with DNS challenge will be the best option.

**Comment by Churro** [comment]
Hi, would be great to have this but it seems to be quite tricky on ESXi, see https://github.com/w2c/letsencrypt-esxi/issues/2

**Comment by MrakCZ** [comment]
Oh, I am sorry, I missed the closed threads. Newbie to github using. Thank you for answer.
