### ISSUE TITLE
How to install on ESXI 8 U2 last version ?

### ISSUE THREAD

**Issue by Witawat** [w2c/letsencrypt-esxi#34]
How to install on ESXI 8 U2 last version ?

i try install error 

> [root@localhost:~] esxcli software vib install -v /vmfs/volumes/Data01/w2c-letsencrypt-esxi.vib -f
 [InstallationError]
 Can not open /var/vmware/lifecycle/stageliveimage/data/payload1.t00 to write payload payload1: [Errno 2] No such file or directory: '/var/vmware/lifecycle/stageliveimage/data/payload1.t00'
      cause = Can not open /var/vmware/lifecycle/stageliveimage/data/payload1.t00 to write payload payload1: [Errno 2] No such file or directory: '/var/vmware/lifecycle/stageliveimage/data/payload1.t00'
       vibs = ['web-wack-creations_bootbank_w2c-letsencrypt-esxi_1.1.0-0.0.0']
 Please refer to the log file for more details.

**Comment by Churro** [comment]
Not reproducible on my end.

```sh
[root@esxi8:~] vmware -v
VMware ESXi 8.0.2 build-23825572

[root@esxi8:~] esxcli software vib install -v /tmp/w2c-letsencrypt-esxi.vib
Installation Result
   Message: Operation finished successfully.
   VIBs Installed: web-wack-creations_bootbank_w2c-letsencrypt-esxi_1.1.0-0.0.0
   VIBs Removed:
   VIBs Skipped:
   Reboot Required: false
   DPU Results:

[root@esxi8:~] cat /var/log/syslog.log | grep w2c
2024-06-24T17:16:46.862Z In(30) .etc.init.d.w2c-letsencrypt[133237]: Running 'start' action
2024-06-24T17:16:46.882Z In(30) .opt.w2c-letsencrypt.renew.sh[133243]: Starting certificate renewal.
2024-06-24T17:16:46.923Z In(30) .opt.w2c-letsencrypt.renew.sh[133256]: Existing cert for some.host.com not issued by Let's Encrypt. Requesting a new one!
2024-06-24T17:17:03.689Z In(30) .opt.w2c-letsencrypt.renew.sh[133306]: Success: Obtained and installed a certificate from Let's Encrypt.
2024-06-24T17:17:05.790Z In(30) .etc.init.d.w2c-letsencrypt[133639]: Running 'install' action
```

**Comment by Witawat** [comment]
this insall on vmware demo or real server ?

**Comment by horfic** [comment]
its a real server.

The issue based on your output lies with the new lifecycle manager. I was quickly able to find a similar issue https://github.com/lamw/ghettoVCB/issues/308

which points that esxi was lacking memory at that user

**Comment by Witawat** [comment]
i use (Updated) ESXi-8.0U2c-23825572-standard (Dell Inc.) or R620 can support ?

**Comment by horfic** [comment]
that is not the issue, did you read the linked ticket?

do you got enough memory for esxi?

**Comment by Witawat** [comment]
> that is not the issue, did you read the linked ticket?
> 
> do you got enough memory for esxi?

now i can install ok 

![image](https://github.com/w2c/letsencrypt-esxi/assets/4926369/2b9b4570-9eaa-4e04-a8cb-90a6d734bb60)

but i add subdomain and ssl not work ?

ok i fix it 
can use 

/etc/init.d/w2c-letsencrypt start

and wait..

thankyou
