### ISSUE TITLE
Support for ESXi 8.0

### ISSUE THREAD

**Issue by kuduka** [w2c/letsencrypt-esxi#6]
Installing VIB on ESXi 8.0 doesn't work, how feasible is repacking the vib with the community tool to support sha-256 gunzip encryption?

# esxcli software vib install -v /tmp/w2c-letsencrypt-esxi.vib -f

 [ProfileValidationError]
 In ImageProfile (Updated) ESXi-8.0.0-20513097-standard, the payload(s) in VIB web-wack-creations_bootbank_w2c-letsencrypt-esxi_1.0.0-0.0.0 does not have sha-256 gunzip checksum. This will prevent VIB security verification and secure boot from functioning properly. Please remove this VIB or please check with your vendor for a replacement of this VIB

**Comment by Churro** [comment]
Adding a sha256 checksum should be doable. I'll see what it needs 👍

**Comment by Churro** [comment]
A new release is now available, providing compatibility with ESXi 8.0
