### ISSUE TITLE
VMware ESXi 7.0 Update 3i - Keeping Self Signed Cert

### ISSUE THREAD

**Issue by war59312** [w2c/letsencrypt-esxi#9]
I upgraded to VMware ESXi 7.0 Update 3i from VMware ESXi 7.0 Update 3g, but it is now keeping Self Signed Cert.

VMware ESXi 7.0 Update 3i uses Client version: 2.1.1. 

VMware ESXi 7.0 Update 3g Client version: 1.43.8.

Despite log showing success:

```
[will@esxi:~] cat /var/log/syslog.log | grep w2c
2022-12-15T23:41:28.191Z jumpstart[2098126]: executing start plugin: w2c-letsencrypt
2022-12-15T23:41:28.194Z .etc.init.d.w2c-letsencrypt[2100127]: Running 'start' action
2022-12-15T23:41:28.212Z .opt.w2c-letsencrypt.renew.sh[2100141]: Starting certificate renewal.
2022-12-15T23:41:28.280Z .opt.w2c-letsencrypt.renew.sh[2100167]: Existing cert for esxi.mydomain.com not issued by Let's Encrypt. Requesting a new one!
2022-12-15T23:41:40.059Z jumpstart[2098126]: w2c-letsencrypt started.
2022-12-15T23:41:44.512Z .opt.w2c-letsencrypt.renew.sh[2100734]: Success: Obtained and installed a certificate from Let's Encrypt.
```

FYI, Not sure why, but have to use `wget --no-check-certificate` to grab the file:

```
[will@esxi:~] wget -O /tmp/w2c-letsencrypt-esxi.vib https://github.com/w2c/letsencrypt-esxi/releases/latest/download/w2c-letsencrypt-esxi.vib
Connecting to github.com (140.82.114.3:443)
wget: error getting response

[will@esxi:~] wget --no-check-certificate -O /tmp/w2c-letsencrypt-esxi.vib https://github.com/w2c/letsencrypt-esxi/releases/latest/download/w2c-letsencrypt-esxi.vib
Connecting to github.com (140.82.114.4:443)
Connecting to github.com (140.82.114.4:443)
Connecting to objects.githubusercontent.com (185.199.109.133:443)
saving to '/tmp/w2c-letsencrypt-esxi.vib'
w2c-letsencrypt-esxi 100% |*********************************************************************************************************************************************************************| 29770  0:00:00 ETA
'/tmp/w2c-letsencrypt-esxi.vib' saved
```
Upgrade of the script looks good:

```
[will@esxi:~] esxcli software vib install -v /tmp/w2c-letsencrypt-esxi.vib -f
Installation Result
   Message: The update completed successfully, but the system needs to be rebooted for the changes to be effective.
   Reboot Required: true
   VIBs Installed: web-wack-creations_bootbank_w2c-letsencrypt-esxi_1.1.0-0.0.0
   VIBs Removed: web-wack-creations_bootbank_w2c-letsencrypt-esxi_1.0.0-0.0.0
   VIBs Skipped:
[will@esxi:~] esxcli software vib list | grep w2c
w2c-letsencrypt-esxi           1.0.0-0.0.0                            web-wack-creations  CommunitySupported  2022-09-27
reboot
w2c-letsencrypt-esxi           1.1.0-0.0.0                            web-wack-creations  CommunitySupported  2022-12-15
```

Well looks like the Let's Encrypt cert is there (Host > Manage > Security & users > Certificates). but the web ui needs to be restarted for it to take effect.

Indeed, I just ran `/sbin/services.sh restart` and now the web ui is using the certificate.

So looks like this command needs to be ran at the end of the cert install.

**Comment by Churro** [comment]
`2022-12-15T23:41:44.512Z .opt.w2c-letsencrypt.renew.sh[2100734]: Success: Obtained and installed a certificate from Let's Encrypt.` is a good sign and followed by a restart of all the Web UI + services that use the certificate:
https://github.com/w2c/letsencrypt-esxi/blob/27598a9070e7c691b1dce36786d70679cb0776ad/renew.sh#L108

So, triggering `/sbin/services.sh restart` in addition shouldn't be necessary. The strange thing though is why it installed the certificate in your case but didn't restart the corresponding services. 

- Could you please provide the log lines after `Success: Obtained and installed a certificate from Let's Encrypt.`? They should also indicate that services have been restarted. 
- Could you please issue the restart command from `renew.sh` (as shown above) manually to see if it works on your installation of ESXi 7.0?

Unrelated to that, I remember having seen as well that sometimes ESXi fails to verify the TLS connection to github.com. An alternative to the insecure `wget --no-check-certificate` call would be to manually upload the VIB file.

**Comment by ghost** [comment]
works perfectly on esx 8 
thanks

**Comment by war59312** [comment]
Alright...

Sorry for late reply. Holidays. Happy new year.

Finally got around to upgrading a second host and I did NOT run into this issue. So looks like a 1 off.

FYI `Success: Obtained and installed a certificate from Let's Encrypt.` is the last line of the log.

Closing since it sems was just an odd 1 off.

**Thanks again.**
